name: Docker Tests (PostgreSQL)

on:
  workflow_call:

jobs:
  run-docker-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # docker-testが build, pstg, e2e を実行する
        test_target: [build-test, pstg-test, e2e-test]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup test environment
        uses: ./.github/actions/setup-test-env

      - name: Run docker tests (USE_SQLITE=false)
        env:
          SUDO: 'true' # CI環境でdockerコマンドにsudoを付与
        # Makefileターゲットが USE_SQLITE=false を強制設定する
        run: make ${{ matrix.test_target }}